version: '3.3'
 
services:
  mysql_dev:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_dev
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "cinema"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "cinema_app_dev"
  # mysql_test:
  #   image: mysql/mysql-server
  #   command: --default-authentication-plugin=mysql_native_password
  #   container_name: mysql_test
  #   ports:
  #     - 3308:3306
  #   environment:
  #     MYSQL_USER: "cinema"
  #     MYSQL_PASSWORD: "password"
  #     MYSQL_DATABASE: "cinema_app_test"