version: '3.3'
 
services:
  mysql:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "cinema"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "cinema_app"